### ISSUE TITLE
New stable release before merging?

### ISSUE THREAD

**Issue by astratto** [sinatra/rack-protection#118]
Hi,

I've noticed that rack-protection is now part of Sinatra's master.
Are you planning on releasing a final version independent from that repo for everyone not willing to migrate to a beta version of Sinatra?

There are a few patches that are just in master from what I can see (i.e., allow_if for HttpOrigin).

**Comment by danleyden** [comment]
That sounds like a good idea to me... If there were a 1.99 release of everything prior to closing the project, that would be really useful to those of us who aren't ready to make the bigger jump to Sinatra 2. Particularly while it is still so new.

**Comment by zzak** [comment]
Even though the source has moved to Sinatra, it's not dependent on sinatra directly.

Rack is the only dependency for `rack-protection`: https://github.com/sinatra/sinatra/blob/master/rack-protection/rack-protection.gemspec#L85

As far as another 1.x release, I would only consider if there was a critical bug found in those versions. But basically everything committed since 1.5.3 has been features, you're free to upgrade at your leisure. _edit_: wrong r-p version mentioned

**Comment by zzak** [comment]
btw, here is the diff from the last stable release until the merge took place: https://github.com/sinatra/rack-protection/compare/v1.5.3...pre-merge

**Comment by astratto** [comment]
@zzak thanks for the reply.
Sorry, I was under the impression that rack-protection was not going to be released as gem anymore.
I'd actually need some of the patches that have not been released yet (i.e., allow_if for HttpOrigin), but I'll wait and find another way for now.

Thanks again.

**Comment by zzak** [comment]
@astratto Are you able to use the `2.0.0.beta2` release?

**Comment by astratto** [comment]
@zzak I can surely play with it if you need me to, but using a beta version is definitely not an option for me.

**Comment by zzak** [comment]
@astratto Sure! You don't have to put it in production, but put it in your gemspec and run your tests for me at the very least :bow:
