### ISSUE TITLE
Session Hijacking default of HTTP_ACCEPT_LANGUAGE is broken for IE with XHR

### ISSUE THREAD

**Issue by t-cyrill** [sinatra/rack-protection#96]
I found the IE's XHR send different Accept-Language header with browsing.

When non XHR request like this:

```
Accept: text/html, application/xhtml+xml, */*
Accept-Language: ja-JP
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
```

But XHR like this:

```
x-requested-with: XMLHttpRequest
Accept-Language: ja
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/json
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
```

This difference causes trouble with session reset in XHR request.

Thank you.

**Comment by kytrinyx** [comment]
Thank you for reporting this. I need to make sure I understand the problem correctly:

Since the `Accept-Language` header value is different between XHR and non-XHR requests, the `Rack::Protection::SessionHijacking` middleware kicks in, because it makes the assumption that a different value here is someone trying to spoof a session.

The result is that the user gets logged out if an XHR request is made.

Is this correct?

I'm not sure what the best approach to take in this situation is. If we match only on the [ISO 639-1 code](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) then `Rack::Protection::SessionHijacking` will be more permissive, which might not be desirable.

**Comment by zzak** [comment]
Closing for no feedback.

I'm also not sure what to do in this situation, but open to suggestions (in the form of a patch :+1:) But it sounds to me like being more permissive of `Accept-Language` header should be ok?

Thanks and sorry for any trouble this has caused you!
